### ISSUE TITLE
gtklock on Hyprland

### ISSUE THREAD

**Issue by nova-nowiz** [conrad-mo/hyprland-dot#3]
Hi!
I'm setting up gtklock at the moment on Hyprland
did you have any issue with it?
Mine doesn't want to succeed even if I copy/paste my password (which is possible when using `gtklock -li` for debug)
Thanks!

**Comment by conrad-mo** [comment]
Strange, gtklock works perfectly for me with no issues

Can you show me your log when u run it with debug

**Comment by nova-nowiz** [comment]
That's the issue, there's no log xD
no error message or anything
And I don't know how to get that, I posted an issue here: https://github.com/jovanlanik/gtklock/issues/50
At least I now know it's supposed to work on Hyprland so thanks!

**Comment by conrad-mo** [comment]
> That's the issue, there's no log xD no error message or anything And I don't know how to get that, I posted an issue here: [jovanlanik/gtklock#50](https://github.com/jovanlanik/gtklock/issues/50) At least I now know it's supposed to work on Hyprland so thanks!

Yeah I also get no log whenever I have the wrong pw. Gtklock worked out of the box for me

**Comment by nova-nowiz** [comment]
Must be a NixOS related issue then, thank you very much for all the info!

**Comment by nova-nowiz** [comment]
Damn it, it is... 
> Important note: for gtklock to work you need to set "security.pam.services.gtklock = {};" manually.

can confirm that it now works perfectly
